<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0-preview.7.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-preview.7.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crm.Clients.Application\Crm.Clients.Application.csproj" />
    <ProjectReference Include="..\Crm.Clients.Infrastructure\Crm.Clients.Infrastructure.csproj" />
  </ItemGroup>
</Project>
