<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>NU1603</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crm.Clients.Domain\Crm.Clients.Domain.csproj" />
    <ProjectReference Include="..\Crm.Clients.Application\Crm.Clients.Application.csproj" />
    <ProjectReference Include="..\..\..\..\shared\Crm.Shared.Infrastructure\Crm.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
