<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crm.Analytics.Domain\Crm.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\shared\Crm.Shared.DTOs\Crm.Shared.DTOs.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0-preview.7.25380.108" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0-preview.7.25380.108" />
  </ItemGroup>
</Project>
